### PR TITLE
Hotfix for Nya memory leak issues..

### PR DESCRIPTION
**Pull request by FrozenAlex**
Version  bump of shame

### CODE REVIEW

**Comment by ComputerElite** [comment]
Please use this to add new versions for the mod https://computerelite.github.io/tools/Beat_Saber/modsjsongenerator.html

**Comment by FrozenAlex** [comment]
Wait, should I keep the old versions of the mod in the index? Also the tool does not really replace the old mod versions and does not sort the mods by name. Not sure how I should use it.

**Comment by ComputerElite** [comment]
Yeah, you should keep the old version in the json file and thus doesn't replace the old mod version

**Comment by FrozenAlex** [comment]
image
image

mods.json some duplicate mod entries.. Script could use duplicate check to update the mod with the same version prolly.

So it becomes this if I understand you correctly. I just have two
image
I just want to replace it because I do not want anyone to download the old version.

**Comment by ComputerElite** [comment]
Okay you can replace it for now until I add duplicate checks back in. I used to have some

**Comment by ComputerElite** [comment]
Duplicates now don't get shown (whichever entry has the higher version gets shown). I added back the old Nya version. Thanks for actively helping the mods site stay up to date

**Pull request merged**
