### PR TITLE
Add check to ensure the game version listed is in the core mods

### PR DESCRIPTION
**Pull request by AltyFox**

### CODE REVIEW

**Comment by ComputerElite** [comment]
I remember there being an array with hidden game versions. Please move the check you added to the same location where the other check is performed

**Comment by AltyFox** [comment]
> I remember there being an array with hidden game versions. Please move the check you added to the same location where the other check is performed

You have an empty array that gets called twice. Your code checks if an item exists in that array and returns. 
The hidden game versions array is defined, and referenced twice. No check is performed. Referencing that array. 

I can change this to do a check and continue using that array, but as of right now, there is no other check being performance

**Comment by AltyFox** [comment]
So placing the code inside the add game versions function seemed logical

**Comment by AltyFox** [comment]
I'll just create a method to automatically populate hidden game versions, it won't be that hard

**Pull request merged**
